# Data Pre-Processing
Step:1


Remove Null values and feature standardization.

In [0]:
import pandas as pd
from sklearn.preprocessing import Imputer

In [6]:
from google.colab import files
uploaded = files.upload()

Saving Data.csv to Data.csv

In [18]:
df=pd.read_csv('Data.csv')
df.head()
df[['Age','Salary']]

    Age   Salary
0  44.0  72000.0
1  27.0  48000.0
2  30.0  54000.0
3  38.0  61000.0
4  40.0      NaN
5  35.0  58000.0
6   NaN  52000.0
7  48.0  79000.0
8  50.0  83000.0
9  37.0  67000.0

In [20]:
imuter = Imputer(missing_values='NaN', strategy='mean')
df[['Age','Salary']] = imuter.fit_transform(df[['Age','Salary']])
df.head()

/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:66: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)

   Country   Age        Salary Purchased
0   France  44.0  72000.000000        No
1    Spain  27.0  48000.000000       Yes
2  Germany  30.0  54000.000000        No
3    Spain  38.0  61000.000000        No
4  Germany  40.0  63777.777778       Yes

# Replacing Categorial Data with Numeric Data

In [0]:
from sklearn.preprocessing import LabelEncoder

In [27]:
label_encoder=LabelEncoder()
df['Country'] = label_encoder.fit_transform(df['Country'])
df['Purchased'] = label_encoder.fit_transform(df['Purchased'])
df.head()

   Country   Age        Salary  Purchased
0        0  44.0  72000.000000          0
1        2  27.0  48000.000000          1
2        1  30.0  54000.000000          0
3        2  38.0  61000.000000          0
4        1  40.0  63777.777778          1

In [28]:
df.tail()

   Country        Age   Salary  Purchased
5        0  35.000000  58000.0          1
6        2  38.777778  52000.0          0
7        0  48.000000  79000.0          1
8        1  50.000000  83000.0          0
9        0  37.000000  67000.0          1